language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-simple-node-package' ]; then cd .. && eval "mv $currentfolder generator-simple-node-package" && cd generator-simple-node-package; fi

